-- Inital Data Load For `public.insult` table. Contaims all the initial jokes.
-- In Produdction - This will be replade with a routine backup snapshot of the database, that should be used for recovery efforts
INSERT INTO "insults"(explicit,added_by_id,category,added_on, content, status)   VALUES
('FALSE','1','B','2022-12-14','Yo mama so bald, you can see what’s on her mind.','A'),
('FALSE','1','B','2022-12-14','Yo momma is so bald... you can see what''s on her mind.','A'),
('FALSE','1','B','2022-12-14','Yo momma is so bald... even a wig wouldn''t help!','A'),
('FALSE','1','B','2022-12-14','Yo momma is so bald... she had to braids her beard.','A'),
('FALSE','1','B','2022-12-14','Yo momma is so bald... everyone thought the sun was rising when she got up.','A'),
('FALSE','1','B','2022-12-14','Yo momma is so bald... Mr. Clean was jealous.','A'),
('FALSE','1','B','2022-12-14','Yo momma is so bald... that she took a shower and got brainwashed.','A'),
('FALSE','1','DO','2022-12-14','Yo daddy so old, his Social Security number is 4.','A'),
('FALSE','1','DS','2022-12-14','Yo daddy is so dumb he turned down a blowjob because he thought it would mess up his unemployment check.','A'),
('FALSE','1','DS','2022-12-14','Yo daddy so dumb, somebody said it was chilly outside so he went to get a bowl.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid that she thought Star Wars was a war for stars.','A'),
('FALSE','1','S','2022-12-14','Yo mama''s so stupid, when they said ''Order in the court'', she asked for fries and a shake.,','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she trips over the wireless internet.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumbshe called me to ask for my phone number.','A'),
('FALSE','1','S','2022-12-14','Yo mama soything dumb when your dad said it was chilly outside, she ran outside with a spoon.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid, she couldn’t read an audiobook.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she got locked in Furniture World and slept on the floor.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she worked at a M&M factory and threw out all the W''s.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she put a watch in a piggybank and said she was saving time.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she can''t pass a blood test.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she sits on the floor and watches the couch.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she ordered a cheeseburger without the cheese.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb she thought a quarterback was a refund.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb she cooks her own complimentary breakfast.','A'),
('FALSE','1','S','2022-12-14','Yo mama''s so stupid when thieves broke into her house and stole the TV, she chased after them shouting ''Wait! You forgot the remote!'',','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she went to the library to find Facebook.','A'),
('FALSE','1','S','2022-12-14','Yo mama’s so stupid she thought fortnite was fork night.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she cooked her own complimentary breakfast.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she tried to eat Eminem the rapper.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... when they said that it is chilly outside, she went outside with a bowl and a spoon.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she puts lipstick on her forehead to make-up her mind.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she thought KFC was UFC for chickens.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she failed a survey.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid she thought light sabers had less calories.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... that she burned down the house with a CD burner.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid, she sold the house to pay the mortgage.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she got lost in a telephone booth.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she stopped at a stop sign and waited for it to turn green.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... it took her 2 hours to watch 60 seconds.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, when she heard about cookies on the Internet, she ate her computer.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she stole free bread.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb she sold her car to get gasoline money!','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid, she went to the dentist to get Bluetooth.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid, she got locked in a mattress store and slept on the floor.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid, she studied for a Covid test.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb when you stand next to her you hear the ocean!','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she got fired from the M &amp; M factory for throwing away all the W’s.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she tried to commit suicide by jumping out the basement window.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid, she took a ruler to bed to see how long she slept.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, it takes her an hour to cook minute rice.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, when the doctor told her she had coronavirus, she bought a new laptop.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she got locked in a grocery store and starved.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... when she asked me what kind of jeans am I wearing I said, ''Guess'', and she said, ''Levis''.','A'),
('FALSE','1','S','2023-01-30','“Yo mama’s so stupid she told me to meet her at the corner of Walk and Don’t Walk.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she sold her car for gas money.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid, she returned a doughnut because it had a hole in it.','A'),
('FALSE','1','S','2022-12-14','Yo momma is so stupid... she put lipstick on her forehead to make up her mind.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she put sugar on the bed because she wanted sweet dreams.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb that she spent hours starting at a glass of orange juice because it said ''concentrate'' on the package.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb it takes her twenty minutes to cook minute rice.','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb that she thought, Dunkin'' Donuts was a basketball team!','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she tried to eat Eminem!,','A'),
('FALSE','1','S','2022-12-14','Yo mama so dumb, she thought Twitter was social media for birds.','A'),
('FALSE','1','S','2022-12-14','Yo mama so stupid, she climbed over a glass wall to see what was on the other side.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she bungee jumps she goes straight to hell!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she left in high heels and came back in flip flops.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat she can’t reach her back pocket.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she gets on the elevator it says, ''cNext stop, Hell''d!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when you go around her you get lost!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she wakes up on both sides of the bed.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she took her shirt off at the strip club, everyone thought she was Jabber the Hut from Star Wars.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she went bungee jumping in a yellow dress, everyone was screaming the suns falling!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she goes to the car wash to take showers.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, a picture of her would fall off the wall!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat she needs two watches for two different time zones.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, if she got her shoes shined, she’d have to take his word for it!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she fell in love</a> and broke it.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she has wants someone to shake her hand, she has to give directions!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she left in high heels and came back in flip flops.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she jumps up in the air she gets stuck!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she has more chins than a Chinese phone book.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she gets group insurance!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... it took me a bus and two trains just to get on her good side.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when she got hit by a bus she asked, “Who threw that rock?”','A'),
('FALSE','1','F','2022-12-14','Yo mama so big, when she talks to herself it’s a long-distance call.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when she walked past the TV, I missed three episodes.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when a bus hit her she said, ''Who threw the pebble?''','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, that when she hauls ass it takes her two trips.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat when she goes camping, the bears hide their food.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she uses an air balloon for a parachute.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she takes a bath she fills the tub then turns on the water.','A'),
('FALSE','1','F','2022-12-14','Yo mama is so fat she poured two drops of water into the tub and got it. It still overflowed.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she wears a red dress all the kids scream look it''9s the Kool-Aid man.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when she crossed the road people mistook her for a roundabout.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she had to be baptized at sea world.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she eats Wheat Thicks.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... you could use her bellybutton as a wishing well.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... that she needs a bookmark to keep track of all her chin rolls!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, and old, that when God said ''Let there be light,'' he was just asking her to move out of the way.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... the back of her neck is like a pack of hot dogs!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, her job title is Spoon and Fork Operator!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she put on her lipstick with a paint roller.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... whenever she goes to the beach the tide comes in!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... the last time she saw 90210 was on the scale!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she broke a branch in her family tree!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she steps on the scale it says we don''t do livestock.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when God said, ''cLet there be light,''d he had to ask her to move out of the way.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she had her ears pierced by harpoon.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when stepped on the scale it said, ‘To be continued.’','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... they had to install speed bumps at all you can eat buffets.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when she skips a meal, the whole stock market drops.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... that when she wanted a waterbed, they had to put a cover over the Atlantic Ocean.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she''s got to wake up in sections.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she went to the movies and sat next to everyone.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she looks like she''s smuggling an SUV!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat when she tripped over on 4th Ave, she landed on 12th.','A'),
('FALSE','1','F','2022-12-14','Yo mama''s so fat that even Dora don''t have time to explore her!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she sat on a tractor and made a pick-up truck.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she jumped off the Grand Canyon and got stuck.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she goes to an amusement park, people try to ride her!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she uses the interstate as a slip and slide.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, Thanos had to clap.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she puts on her yellow rain coat and walks down the street people shout out ''ctaxi''d!','A'),
('FALSE','1','F','2023-01-30','“Yo mama’s so fat that when she walked past the TV, I missed three episodes.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she sits on the beach, whales swim up to her and sing we are family...!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... her nickname is Lardo.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... every time she walks in high heels, she strikes oil!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat that when she sat on an iPhone it turned into an iPad.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she uses Google Earth to take a selfie.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she sat on a rainbow and made skittles.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she has seat belts on the chairs to keep her fat from rolling off!','A'),
('FALSE','1','F','2022-12-14',' Yo mama so fat when she got on the scale it said, ''I need your weight not your phone number''.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she lays on the beach and people run around yelling Free Willy!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she wore a blue and green sweater, everyone thought she was Planet Earth.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she jumped in the air and got stuck.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when she takes a shower, her feet don’t get wet!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... the government forced her to wear taillights and blinkers so no one else would get hurt.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she turns around they throw her a welcome back party.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat that her official job title is spoon and fork operator.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she goes to Taco Bell, they run for the border!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, I took a picture of her last Christmas and the damn thing''s still printing.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she supplies 99% of the world''9s gas.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when she gets in an elevator, it HAS to go down!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... NASA has to orbit a satellite around her!','A'),
('FALSE','1','F','2022-12-14','Yo mama''s so fat that when she walked past the TV I miss three episodes.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when she buys a fur coat, a whole species goes extinct.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she rolled over 4 quarters and made a dollar!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she goes to a restaurant, looks at the menu, and says, ''okay!''','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she was floating in the ocean and Spain claimed her for their new world.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat that when she hauls ass, she has to make two trips!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she rolled out of bed and everybody thought there was an earthquake.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, when God said, “Let there be light,” he asked her to move out of the way.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat that her belt size is ''equator''!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... her measurements are 26-34-28, and her other arm is just as big!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she makes Godzilla look like an action figure.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she was in school she sat next to everybody!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when her beeper goes off, people think she is backing up.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she bungee jumps, she brings down the bridge too.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she walked in front of the TV and I missed 3 shows.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she lays on the beach no one else gets sun!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat that she needs to take our group insurance when she travels.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, she makes Godzilla look like an action figure.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she sank the Titanic!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she dives into the ocean, there is a tsunami-warning!','A'),
('FALSE','1','F','2023-01-30','Yo mama’s so fat, when she stepped on the scale it said, ‘To be continued.’','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat she sat on a dollar and when she got up there was 4 quarters.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she makes a whale look bulimic!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she was floating in the ocean and Spain claimed her for the new world!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she plays hopscotch, she goes North America, Europe, Asia.','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat when she tried to weight herself and the scales said ''one at a time please''. ','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat, even Dora can’t explore her.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... people jog around her for exercise.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... when she steps on a scale, it read, ''cone at a time, please''d.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she''s got her own area code!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she was going to Wal-Mart, tripped over Kmart, and landed right on Target!!!','A'),
('FALSE','1','F','2022-12-14','Yo mama so fat that when she orders a fur coat an entire species goes extinct.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... the highway patrol made her wear ''Caution!, Wide Turn!''','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she needs a watch on both arms because she covers two time zones.','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... her husband has to stand up in bed each morning to see if it''s daylight!','A'),
('FALSE','1','F','2022-12-14','Yo momma is so fat... she fell and made the Grand Canyon!','A'),
('FALSE','1','H','2022-12-14','Yo momma is so hairy... that Bigfoot tried to take her picture!','A'),
('FALSE','1','H','2022-12-14','Yo momma is so hairy... she wears a Nike tag on her weave so now everybody calls her Hair Jordan.','A'),
('FALSE','1','H','2022-12-14','Your mother''s arms are so hairy, when she walks down the street it looks like she has Buckwheat in a headlock.','A'),
('FALSE','1','H','2022-12-14','Yo momma is so hairy... the zoo offered to buy her kids.','A'),
('FALSE','1','H','2022-12-14','Yo momma is so hairy... Harry Potter got jealous.','A'),
('FALSE','1','H','2022-12-14','Yo momma is so hairy... she has cornrows on her back, legs, and feet!','A'),
('FALSE','1','H','2022-12-14','Yo momma is so hairy... she shaves with a weed-eater.','A'),
('FALSE','1','H','2022-12-14','Yo momma is so hairy... you almost died of rug burn at birth!','A'),
('FALSE','1','H','2022-12-14','Yo mama so hairy people think she’s an Ewok.','A'),
('FALSE','1','H','2022-12-14','Yo momma is so hairy... her tits look like coconuts.','A'),
('FALSE','1','L','2022-12-14','Yo momma is so lazy... she starved instead of getting up to get some food.','A'),
('FALSE','1','L','2022-12-14','Yo momma is so lazy... that she came in last place in a recent snail marathon.','A'),
('FALSE','1','L','2022-12-14','Yo momma is so lazy... she arrived late at her own funeral.','A'),
('FALSE','1','L','2022-12-14','Yo mama so lazy she stands outside to let the wind blow her nose!','A'),
('FALSE','1','L','2022-12-14','Yo mama so lazy, she has a stay-at-home job and still is late to work.','A'),
('FALSE','1','L','2022-12-14','Yo momma is so lazy... she thinks a two-income family is where the man has two jobs.','A'),
('FALSE','1','L','2022-12-14','Yo momma is so lazy... she''s got a remote control just to operate her remote!','A'),
('FALSE','1','L','2022-12-14','Yo mama so lazy, she stuck her nose out the window so the wind could blow it.','A'),
('FALSE','1','L','2022-12-14','Yo mama so lazy she woke up from a coma and went to sleep.','A'),
('FALSE','1','N','2022-12-14','Yo mama is nasty. When she went to take a bath, the water jumped out and said, ''That''s okay, I''ll wait.''','A'),
('FALSE','1','N','2022-12-14','Yo mama so nasty, she went swimming and made the Dead Sea.','A'),
('FALSE','1','N','2022-12-14','Yo mama is so nasty she swam the Ink Sea and left a dark streak.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old she still owes Moses a quarter!','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... I told her to act her own age, and she died.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... her social security number is 1!','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she knew the Great Wall of China when it was only good!','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she knew Burger King while he was still a prince.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she ran track with dinosaurs.','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old she has a picture of Abraham carved into her yearbook.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... her birth certificate says expired on it.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... that her bus pass is in hieroglyphics!','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... that when she was in school there was no history class.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she has a picture of Moses in her yearbook.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... her social security number is 1!','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old her driver''s license is written with Roman numerals.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, she walked into an antique store and they kept her.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... her birth certificate is in Roman numerals.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she was wearing a Jesus starter jacket!','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, she walked into an antiques store, and they didn’t let her leave.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... that her bus pass is in hieroglyphics!','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, when someone told her to act her age, she died.','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old she took her driving test on a triceratops!','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old her first car was a chariot!','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old she helped write the ten commandments.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she has a picture of Moses in her yearbook.','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old she cleaned up after the last supper.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she was wearing a Jesus starter jacket!','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she ran track with dinosaurs.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... her birth certificate is in Roman numerals.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, when she was young, rainbows were still black and white.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, when she was born, the Dead Sea was still just getting sick.','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old she got sold while looking around the antique store!','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she knew the Great Wall of China when it was only good!','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, Jurassic Park brings back memories.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... I told her to act her own age, and she died.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, her birth certificate says expired on it.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, she was a waitress at the Last Supper.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... that when she was in school there was no history class.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, she knew Burger King when he was a prince.','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... she knew Burger King while he was still a prince.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, her birth certificate is in Roman numerals.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, her driver’s license got hieroglyphics on it!','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old she knew burger king when he was still a prince.','A'),
('FALSE','1','O','2022-12-14','Yo mama''s so old she still owes Moses money.','A'),
('FALSE','1','O','2022-12-14','Yo mama so old, when the preacher asked if she knew Jesus, she said, ''Know him? Motherfucker still owes me five dollars.''','A'),
('FALSE','1','O','2022-12-14','Yo momma is so old... her birth certificate says expired on it.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she can''t afford to pay attention!','A'),
('FALSE','1','P','2022-12-14','Yo mama house so small, you have to go outside to change your mind.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... I walked in her house and stepped on a cigarette, and your mom said, ''Who turned off the lights?''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... I walked in her house and stepped on a cigarette, and your mom said, ''Who turned off the lights?''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when I ring the doorbell she says, ''[DING!''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she was in Walmart with a box of Hefty bags. ''I said, what ya doing?'', She said, ''Buying luggage.''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... the roaches pay the light bill!','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when I ring the doorbell she says, ''[DING!''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she waves around a popsicle stick and calls it air conditioning.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... I stepped in her house and I was in the backyard.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when I saw her kicking a can down the street, I asked her what she was doing, she said, ''Moving''.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she waves around a popsicle stick and calls it air conditioning.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when her friend came over to use the bathroom she said, ''Ok, choose a corner.''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... the roaches pay the light bill!','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when I ring the doorbell she says, ''[DING!''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she was in Walmart with a box of Hefty bags. ''I said, what ya doing?'', She said, ''Buying luggage.''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she waves around a popsicle stick and calls it air conditioning.','A'),
('TRUE','1','P','2022-12-14','Yo mama so poor she can’t even pay attention.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when I saw her kicking a can down the street, I asked her what she was doing, she said, ''Moving''.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... your family ate cereal with a fork to save milk.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... the roaches pay the light bill!','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when her friend came over to use the bathroom she said, ''Ok, choose a corner.''','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she was in Walmart with a box of Hefty bags. ''I said, what ya doing?'', She said, ''Buying luggage.''','A'),
('FALSE','1','P','2022-12-14','Yo mama so poor when I saw her kicking a can down the street, I asked her what she was doing, she said “Moving.”','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she can''t afford to pay attention!','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... I stepped in her house and I was in the backyard.','A'),
('TRUE','1','P','2022-12-14','Yo mama so poor, ducks throw bread at her.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... I walked in her house and stepped on a cigarette, and your mom said, ''Who turned off the lights?''','A'),
('FALSE','1','P','2022-12-14','Yo mama so poor when she goes to the park, ducks throw bread at her!','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when I saw her kicking a can down the street, I asked her what she was doing, she said, ''Moving''.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... when her friend came over to use the bathroom she said, ''Ok, choose a corner.''','A'),
('FALSE','1','P','2022-12-14','Yo mama house so small that when she orders a large pizza, she has to go outside to eat it.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... I stepped in her house and I was in the backyard.','A'),
('FALSE','1','P','2022-12-14','Yo momma is so poor... she can''t afford to pay attention!','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT... she has a job as a teller at a piggy bank.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT... she does backflips under the bed.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT ... she poses for trophies!','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT... she can surf on a popsicle stick.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT... she can use a sock for a sleeping bag.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT... she can sit on a dime and swing her legs.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT ... she has to use a ladder to pick up a dime.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT... she has to use rice to roll her hair up.','A'),
('FALSE','1','SRT','2022-12-14','Yo mama’s so SRT when she plays fortnite she can hide under the freaking store.','A'),
('FALSE','1','SRT','2022-12-14','Yo mama so SRT, she went to see Santa and he told her to get back to work.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT... she can tie her shoes while standing up.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT... she uses a toothpick as pool stick.','A'),
('FALSE','1','SRT','2022-12-14','Yo momma is so SRT ... she can play handball on the curb.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she can dive through a chain-linked fence.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she turned sideways and disappeared.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she swallowed a meatball and thought she was pregnant.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she can hang glide with a Dorito!','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she can see through peepholes with both eyes.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she don’t get wet when it rains.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she uses cotton balls for pillows.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she hula hoops with a cheerio.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she has to run around in the shower just to get wet.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... she has to wear a belt with her spandex pants.','A'),
('FALSE','1','SKN','2022-12-14','Yo momma is so skinny... her nipples touch.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s feet are so scaly... you can see Crocodile Dundy in her footbath.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama so angry, that McDonalds won''t even serve her happy meals.,','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma is so clumsy... she got tangled up in a cordless phone.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma ain''t got no ears yelling... Let me hear both sides of the story!','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama so chatty, she gave a eulogy at her own funeral.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s house is so small... that when she orders a large pizza she had to go outside to eat it.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma has so many chins... it looks like she''s wearing a fat necklace!','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma is so grouchy... the McDonald''s she works at doesn''t even serve happy meals.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s house is so small... you have to go outside to change your mind.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s house is so poor... I went to knock on her door and a roach tripped me and a rat took my wallet!','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma is cross-eyed and watches TV in stereo.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama''s glasses are so thick she can look at a map and see people waving.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s mouth is so big... she speaks in surround sound.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s glasses are so thick... that when she looks on a map she can see people waving.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma so confusing even Scooby Doo can''t figure her out!','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama’s teeth are so yellow, when she smiles, she puts the sun out of business.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s middle name is Rambo.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma is in a wheelchair and says... ''You ain''t gonna push me around no more!''','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s head is so big... she has to step into her shirts.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s feet are so big... her shoes have to have license plates!','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma is so nasty... cows with mad cow disease run from her.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama so mean, they don’t give her happy meals at McDonalds.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s nose is so big... that her neck broke from the weight!','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s teeth are so yellow... that when she smiles traffic slows down.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama’s teeth so yellow, when she drinks water, it turns into lemonade.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s teeth are so yellow... that when she smiles everyone sings, ''I got sunshine on a cloudy day''','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s teeth are so yellow... I can''t believe it''s not butter.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama so confusing, even Scooby Doo couldn’t solve that mystery.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama so scary, even Voldemort won’t say her name.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama’s glasses are so thick, when she looks at a map, she can see people waving at her.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s nose is so big... she makes Pinocchio look like a cat!','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama''s hair is so SRT she rolls it with rice.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s head is so big... it shows up on radar.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s glasses are so thick... she can see into the future.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma is missing a finger and can''t count past nine.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama so clumsy, she makes Humpty Dumpty look like a gymnast.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama''s cooking is so bad even the homeless send it back.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama’s head so big, she dreams in IMAX.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma is like the sun... you look at her to long you will go blind!','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma''s head is so small... she uses a tea bag as a pillow.','A'),
('FALSE','1','SNWF','2022-12-14','Yo mama so strict, she locked you up in a tower.','A'),
('FALSE','1','SNWF','2022-12-14','Yo momma is so small... that she got her ear pierced and died.','A'),
('FALSE','1','T','2022-12-14','Yo momma is so tall... she has to take a bath in the ocean.','A'),
('FALSE','1','T','2022-12-14','Yo momma is so tall... she high-fived God.','A'),
('FALSE','1','T','2022-12-14','Yo momma is so tall... she tripped over a rock and hit her head on the moon.','A'),
('FALSE','1','T','2022-12-14','Yo momma is so tall... Shaq looks up to her.','A'),
('TRUE','1','T','2022-12-14','Yo momma is so tall... she 69''d bigfoot.','A'),
('FALSE','1','T','2022-12-14','Yo momma is so tall... she can see her home from anywhere.','A'),
('FALSE','1','T','2022-12-14','Yo momma is so tall... she tripped in Denver and hit her head in New York.','A'),
('FALSE','1','T','2022-12-14','Yo momma is so tall... she did a cartwheel and kicked the gates of Heaven.','A'),
('FALSE','1','TEST','2022-12-14','TEST - This Document Shoulds be Found by Catagory: ''Test''','A'),
('FALSE','1','TEST','2022-12-19','TEST - Document Should Be Found By explicit: True and Status: ''Deleted''','X'),
('TRUE','1','TEST','2022-12-14','TEST - This Document Shoulds be Found by explicit: true','A'),
('FALSE','1','TEST','2022-12-14','TEST - This Document Shoulds be Found by Catagory: ''Test''','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... even Rice Krispies won''t talk to her!','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... she tried to take a bath and the water jumped out!','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, when she walks into the dentist, they make her lay face down.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... she made an onion cry.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... for Halloween she trick-or-treats on the phone!','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she makes blind kids cry.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly that she has to trick or treat over the phone.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... The NHL banned her for life.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... her mom had to tie a steak around her neck to get the dogs to play with her.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... that your father takes her to work with him so that he doesn''t have to kiss her goodbye.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... she turned Medusa to stone!','A'),
('FALSE','1','U','2023-01-30','“Yo mama’s so ugly she went into a haunted house and they handed her an application.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she has a sign in her garden saying, ‘Beware of the dog!’','A'),
('FALSE','1','U','2022-12-14','Yo mo''mma is so ugly... she got beat up by her imaginary friends!','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... when she walks down the street in September, people say ''Wow, is it Halloween already?''','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... instead of putting the bungee cord around her ankle, they put it around her neck.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, when she was born the doctor slapped your grandma!','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... she gets 364 extra days to dress up for Halloween.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, people dress up as her for Halloween.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she made an onion cry.,','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... that she scares blind people!','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... when she joined an ugly contest, they said, ''Sorry, no professionals.''','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly that her portraits hang themselves.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she could scare the moss off a rock!','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... when they took her to the beautician it took 12 hours for a quote!','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she turned Medusa to stone.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... just after she was born, her mother said, ''What a treasure!'' And her father said, ''Yes, let''s go bury it!''','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, her birth certificate is an apology letter.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she made an onion cry.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, her own portraits hang themselves.','A'),
('FALSE','1','U','2022-12-14','Yo momma so ugly,  even hello kitty said ''goodbye''!,','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she could scare the chrome off a bumper!','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly that the government moved Halloween to be on her birthday.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, her birth certificate is an apology letter from the condom factory.','A'),
('FALSE','1','U','2022-12-14','Yo momma''s so ugly, when she was born the doctor slapped her parents.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she went into a haunted house and the ghosts ran away.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, when she looks in the mirror, her reflection ducks.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... when she walks into a bank, they turn off the surveillance cameras.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... the government moved Halloween to her birthday.','A'),
('FALSE','1','U','2022-12-14','Yo mama is so ugly she walked into a haunted house and walked out with a job application.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, even Hello Kitty said goodbye.','A'),
('FALSE','1','U','2022-12-14','Yo momma is so ugly... they didn''t give her a costume when she tried out for Star Wars.','A'),
('FALSE','1','U','2022-12-14','Yo mama so ugly, she walked into a Haunted House and walked back out with a job application.','A');
