# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-10-17 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Insult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        error_messages="Insults must have content", max_length=65535
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("P", "Poor"),
                            ("F", "Fat"),
                            ("U", "Ugly"),
                            ("S", "Stupid/Dumb"),
                            ("SNWF", "Snowflake"),
                            ("O", "Old"),
                            ("DO", "Old/Daddy"),
                            ("DS", "Stupid/Daddy"),
                            ("N", "Nasty"),
                            ("T", "Stupid/Dumb"),
                            ("TEST", "Testing"),
                            ("SKN", "Skinny"),
                            ("B", "Bald"),
                            ("H", "Hairy"),
                            ("L", "Lazy"),
                            ("SRT", "Short"),
                        ],
                        max_length=5,
                    ),
                ),
                ("explicit", models.BooleanField(default=False)),
                ("added_on", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("X", "Inactive/Removed"),
                            ("P", "Pending"),
                            ("R", "Rejected"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Insult/Joke",
                "verbose_name_plural": "Insults/Jokes",
                "db_table": "insults",
                "ordering": ["explicit", "category"],
            },
        ),
    ]
