# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-10-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insult",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
