# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0003_insultreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insultreview",
            name="insult_id",
            field=models.IntegerField(),
        ),
    ]
