# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-10-23 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0005_alter_insultreview_insult_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insult",
            options={
                "managed": True,
                "ordering": ["explicit", "category"],
                "verbose_name": "Insult/Joke",
                "verbose_name_plural": "Insults/Jokes",
            },
        ),
    ]
